# Generated by Django 5.0.6 on 2024-06-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_speech', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoiceNote',
        ),
    ]
